version: '3.4'

services:
  sample.server:
    image: ${DOCKER_REGISTRY-}sampleserver
    build:
      context: .
      dockerfile: Sample.Server/Dockerfile
  sample.client:
    image: ${DOCKER_REGISTRY-}sampleclient
    build:
      context: .
      dockerfile: Sample.Client/Dockerfile
  rabbitmq:
    image: rabbitmq:3.7-management
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest